meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: shell
    templates:
      - { release: shell, name: shell }
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set shell networks" ))

networks: (( param "please set networks" ))

properties: {}
